### ISSUE TITLE
bexhill-osm for italia

### ISSUE THREAD

**Issue by orionseye** [Dr-Mx/osm-pois#7]
awesome, nice app. Thx for that.
What setting do i need to change in site.js & other file to make the map and poi lookup available for whole Italy? .. beside var mapBounds?
Obviously, i will need to change to limit bounds within zoom area, something like
`var mapBounds='bbox=' + map.getBounds().toBBoxString();`

Somehow, i couldn't make this work yet

**Comment by Dr-Mx** [comment]
Hi thanks!
The app is only designed to be used on small towns really, the bounding box around Italy would be way too big and the Overpass API would time out before you got any results.  The original project that this is based off allows markers to be loaded as you move the screen - https://github.com/humitos/osm-pois, have a look at that, or https://github.com/marczoutendijk/openpoimap (http://openpoimap.org/)
